# Generated by Django 5.1.5 on 2025-02-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
